- speid/commands/spei.py
- speid/helpers/callback_helper.py
- speid/views.py
- test/cassettes/test_create_order.yaml
- test/cassettes/test_create_order1.yaml
- test/cassettes/test_create_order2.yaml
- test/cassettes/test_create_order3.yaml
- test/test_send_order.py
Crear comando para realizar devolución de transferencia #41
Cambiar método de callback set_status_transaction #40
> Minor fixes

- speid/tables/types.py
> change STP status lookup to a dict

- speid/views.py
- test/test_general.py
> Healthcheck

- migrations/versions/4e043705435c_.py
- speid/tables/transactions.py
- speid/tables/types.py
- speid/views.py
- test/cassettes/test_create_order.yaml
- test/test_receive_order.py
Se envía Liquidación a toda respuesta hacia stp
Se reversan los cambios del anterior commit, debido a errores que mandaban
> Se envía Liquidada a STP

- env.template
- speid/__init__.py
- speid/models/transaction.py
- speid/tasks/__init__.py
- speid/tasks/orders.py
- speid/utils.py
- speid/views.py
- tests/views/cassettes/test_process_transaction.yaml
- tests/views/test_general.py
closes #82 
Endpoints para que las transacciones pendientes, puedan ser procesadas
> Fix for #82

- speid/commands/spei.py
- speid/views.py
- tests/conf_files/SpeiActualizaServices.xsd
- tests/conf_files/stp_wsdl.wsdl
- tests/models/test_transactions.py
- tests/views/test_general.py
closes https://github.com/cuenca-mx/speid-privado/issues/7, #84
> Fix for returns

- speid/models/transaction.py
- tests/models/test_transactions.py
closes https://github.com/cuenca-mx/speid-privado/issues/6
> Fix for lenght of nombre beneficiario

- speid/validations/stp_transaction.py
- tests/validations/test_stp_transaction.py
> fixed float round conversion bug

- speid/models/transaction.py
- speid/views.py
- tests/models/test_transactions.py
- tests/views/test_general.py
> Constraint

- speid/models/transaction.py
- speid/tasks/accounts.py
- speid/validations/account.py
- speid/views.py
- tests/models/test_accounts.py
- tests/models/test_transactions.py
- tests/views/test_general.py
Allows insert transactions with `clave_rastreo:null`  `fecha_operacion: null`
> Sparse index

- speid/models/transaction.py
- speid/validations/speid_transaction.py
https://cuencafinance.slack.com/archives/G011XKCJ1AT/p1587655832006000?thread_ts=1587600307.003600&cid=G011XKCJ1AT
Signed-off-by: Piyush Ajmani <piyush@cuenca.com>
> Removed IVA

- speid/tasks/transactions.py
- tests/tasks/test_transactions.py
> Don't resend transactions

- speid/exc.py
- speid/models/transaction.py
- speid/tasks/orders.py
- tests/tasks/cassettes/test_resend_success_order.yaml
- tests/tasks/test_orders.py
Solve add index to speid_id  closes #133
Solve retry task send_order does not validate status closes #132
> Agrega indice y validacciones

- speid/commands/spei.py
> fix command value enum

- .github/dependabot.yml
- requirements.txt
- speid/models/account.py
- speid/validations/account.py
- tests/commands/cassettes/test_re_execute_transactions.yaml
- tests/commands/test_spei.py
- tests/conftest.py
- tests/models/cassettes/test_create_account.yaml
- tests/models/cassettes/test_create_account_failed.yaml
- tests/models/cassettes/test_send_order.yaml
- tests/models/test_accounts.py
- tests/tasks/cassettes/test_create_account.yaml
- tests/tasks/cassettes/test_create_account_existing_account.yaml
- tests/tasks/cassettes/test_create_order_debit_card.yaml
- tests/tasks/cassettes/test_ignore_invalid_account_type.yaml
- tests/tasks/cassettes/test_resend_not_success_order.yaml
- tests/tasks/cassettes/test_resend_success_order.yaml
- tests/tasks/cassettes/test_update_account_successfully.yaml
- tests/tasks/cassettes/test_worker_with_version_2.yaml
- tests/tasks/test_accounts.py
> Update with pais_nacimiento

- speid/exc.py
- speid/helpers/task_helpers.py
- speid/tasks/orders.py
- tests/helpers/test_task_helpers.py
- tests/tasks/test_orders.py
Si una orden llega en el intervalo de tiempo que stp no realiza liquidaciones, intenta hacer la orden 10 min después
closes #267
> Definir intervalo de operación de stp

- speid/tasks/orders.py
Its a known exception 
closes #281
> Remove unnecessary sentry call

- requirements.txt
manually update stpmex to 3.7.6
closes #309
> dependabot didn't updated it :(

- Makefile
- requirements-dev.txt
- requirements.txt
- speid/helpers/callback_helper.py
- speid/helpers/transaction_helper.py
- speid/models/__init__.py
- speid/models/account.py
- speid/models/helpers.py
- speid/models/transaction.py
- speid/tasks/accounts.py
- speid/tasks/transactions.py
- speid/types.py
- speid/validations/__init__.py
- speid/validations/account.py
- speid/validations/stp_transaction.py
- tests/commands/test_spei.py
- tests/conftest.py
- tests/models/test_accounts.py
- tests/models/test_transactions.py
- tests/tasks/cassettes/test_create_moral_account.yaml
- tests/tasks/cassettes/test_send_transaction_restricted_accounts.yaml
- tests/tasks/test_accounts.py
- tests/tasks/test_orders.py
- tests/tasks/test_transactions.py
- tests/validations/test_stp_transaction.py
- tests/views/conftest.py
- tests/views/test_general.py
> Cuentas morales + restricted accounts

- speid/models/account.py
- speid/models/transaction.py
- speid/tasks/transactions.py
- speid/validations/account.py
- tests/views/test_general.py
agrega `is_restricted` a nivel `Account`
> Restrict all

- speid/tasks/transactions.py
- tests/tasks/test_transactions.py
> handles HTTPError from banxico

- speid/models/transaction.py
- tests/views/test_general.py
> fix min amount in restricted accounts

- speid/tasks/orders.py
- tests/tasks/test_orders.py
> fix bank code errors

- requirements.txt
> bump stpmex

- speid/exc.py
- speid/models/transaction.py
- speid/tasks/orders.py
- tests/tasks/cassettes/test_not_unique_speid_id_are_not_allowed.yaml
- tests/tasks/test_orders.py
> Speididunique

- speid/validations/stp_transaction.py
- tests/commands/test_spei.py
> fix validator
